name: CI

on:
  push:
    branches:
      - main  # ou o nome da sua branch principal

jobs:
  test:
    name: Testes
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout do Código
      uses: actions/checkout@v2
      
    - name: Configuração do Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18
    
    - name: Instalação de Dependências
      run: npm install
    
    - name: Execução dos Testes
      run: npm test  # ou o comando específico para executar os seus testes
